const mongoose = require('mongoose');

const productivityReportSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    type: {
      type: String,
      enum: ['weekly', 'monthly'],
      required: true
    },
    startDate: { type: Date, required: true },
    endDate: { type: Date, required: true },
    summary: { type: String, required: true }, // AI Generated text
    insights: [{ type: String }], // Bullet points of insights generated by AI
    topPerformingDay: { type: Date }, // Day of the week they got the most done
  },
  { timestamps: true }
);

// Scalability: Rapid retrieval for standard dashboard history rendering
productivityReportSchema.index({ user: 1, type: 1, startDate: -1 });

module.exports = mongoose.model('ProductivityReport', productivityReportSchema);
